### ISSUE TITLE
Loading files as matrices

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#1]
I finished yesterday’s work saving the freqWCMX to a file, but the following steps don’t work on the file but on the object. How do I load it back into the object I need (to compute pmi and keep going)?

**Comment by QLVL** [comment]
As shown in the tutorial, you get a pmi_mx when you use MatrixManager.compute_pmi(freqMX) method. This pmi_mx is a scipy sparse matrix. And the file you use pmiMX.saveMatrix2File() to save pmi matrix actually also stores a scipy sparse matrix. The procedure should be:
```python
pmi_mx = MatrixManager.compute_pmi(freqWCMX)
pmiMX =	WCMatrix(corpusName, settings, matrix=pmi_mx, wordDict=wordFile, contextDict=contextFile, fmt='pmi')
```
To reload a pmi matrix (scipy sparse matrix) to an object (better to be a WCMatrix object) in your code, you could use WCMatrix class to create an object by the second line shown before. Just be careful to provide the right wordFile and contextFile which store the corresponding word to id mappings. These two files are the files you used when you last time create the pmi matrix. And remember to provide the matrix format since the default format is 'freq'.
```python
wordFile = "/path/to/your/wordFile"
contextFile = "/path/to/your/contextFile"
pmi_mx_file = "/path/to/your/pmi/matrix"
pmiMX = WCMatrix(corpusName, settings, matrix=pmi_mx, wordDict=wordFile, contextDict=contextFile, fmt='pmi')
```

This is a bit complicated that we need three files for one matrix. But this is the current way to save and load matrices. I am working on another way to save all information into one matrix file. We then, don't need to save and load word to id mappings and scipy/numpy matrices separately.

**Comment by delhikiev** [comment]
Ok, great, that helps for later, but right now I am in the previous step. The last thing I did was
```
cfman = ColFreqManager(corpusName, settings, wordFile=wordFile, contextFile=contextFile)
cfman.makeColFreq()
freqWCMX = cfman.makeWCMatrix()
freqWCMX.saveMatrix2File()
```
and what I want to do now is get freqWCMX back to feed it to MatrixManager.compute_pmi()
Does WCMatrix() work for that as well?

**Comment by delhikiev** [comment]
I am getting a name error.
```
>>> from typetoken.Manager import MatrixManager
>>> freqWCMX = WCMatrix(corpusName, settings, matrix=freqWCMXFile, wordDict=wordFile, contextDict=contextFile)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'WCMatrix' is not defined
```

freqWCMXFile is the path to where the matrix was stored.

**Comment by enzocxt** [comment]
1. Yes, the WCMatrix() also works for frequency matrix, and the default format of WCMatrix is also 'freq'.
2. In your previous import code, also import WCMatrix:
```python
from typetoken.Matrix import WCMatrix
```
then, you can use WCMatrix in your code.
When you need WWMatrix, TCMatrix, TVMatrix later, you have to also import them, like this:
```python
from typetoken.Matrix import WCMatrix, WWMatrix, TCMatrix, TVMatrix
```
Or, import all things in Matrix module (then you can use all classes, methods in Matrix module):
```python
from typetoken.Matrix import *
```
