### ISSUE TITLE
Loading matrices

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#10]
How do I load a matrix from a file in this version? I can't find the instructions in this tutorial and the one from the previous version doesn't work.
I saved the wordtype-by-contextfeature collocation matrix in a file
```
>>>freqMTX.save()
Saving matrix to file:
/home/mariana/COHA-II/COHA.wcmx.freq.json
```
and now I need to retrieve the matrix to go on with the calculations. How should I do it?

**Comment by enzocxt** [comment]
Sorry for the delay.  
There are classes for different formats of matrices. WCMatrix is for collocate frequency matrix and pmi matrix. WWMatrix is for row-wise cos similarity matrix and similarity rank matrix. CCMatrix is for column-wise cos similarity matrix and similarity rank matrix. And for the token level there are also TCMatrix, TTMatrix.  
To load these matrices, use following codes.
```python
>>> filename = "/path/to/output/xxx.wcmx.freq.json"
>>> freqMTX = WCMatrix.load(filename, fmt='freq')
>>> filename = "/path/to/output/xxx.wcmx.pmi.json"
>>> pmiMTX = WCMatrix.load(filename, fmt='pmi')
>>> meta_fname = "/path/to/output/xxx.wwmx.cos.meta"
>>> npy_fname = "/path/to/output/xxx.wwmx.cos.npy"
>>> cosMTX = WWMatrix.load(meta_fname, npy_fname, fmt='cos')
```
Please remember to specify the _fmt_ when loading matrices. This _fmt_ (actually _format_ in Matrix class) attribute is necessary when you save matrices by default name. In the code you illustrate before, the freqMTX must have _format_ of 'freq' otherwise it would not be save by the file name "COHA.wcmx.freq.json".  
Before using WCMatrix, WWMatrix, CCMatrix to load matrices, remember to import them.

**Comment by delhikiev** [comment]
Thank you. Now I run into something else I want to reload and don't know how.
I got to the token level.
I created a tvman object with TokVecManager and then `tvman.make_token_context_position()`, which takes some time...
and then a tcMTX object with `tvman.make_token_context_matrix()`
The tcMTX object is saved in a file and I can load it again, but for the weight matrix I need tvman. How do I save tvman so I don't have to generate it again if I want to create the weight matrix much later?
If I load tcMTX with TCMatrix.load(), I can't use tcMTX for the weight matrix.

**Comment by enzocxt** [comment]
Sorry for the delay.  
I have been working on Stefano's project for the last days, since he will have a meeting on Tuesday.  
First, to be clear, the method `tvman.make_token_context_matrix()` generates a token-context position matrix. And this matrix will be saved default into a _xxx.tcmx.position.json_ file. (Do you think is it better to change this method name to `make_tc_position_matrix()` which is consistent with `make_tc_weight_matrix()`)  
Then, the method `tvman.make_tc_weight_matrix()` generates a token-context weight matrix based on the token-context position (actually boolean is enough here) matrix and type-context weight matrix. So in the model, the token-context weight matrix is saved in the same class object of __TCMatrix__, which is an encapsulated token-context sparse matrix.  You can automatically save this token-context weight matrix to a file named _xxx.tcmx.weight.json_ file. The system of saving matrices to default names is not mature now. So it is better to check the __format__ attribute of a matrix before you save the matrix, as the format attribute affects the filename. You can load this token-context weight matrix by `TCMatrix.load(filename, encoding='utf-8', fmt='NAN')`, and remember to pass the correct _fmt_ ('weight' here) parameter.
I have modified `make_tc_weight_matrix()` method from instance method to class method. Now you could use this method to generate token-context weight matrix based on tcPositionMatrix and tcWeightMatrix.
```python
tcWeightMatrix = TokVecManager.make_tc_weight_matrix(tcPosMatrix, twMatrix)
```
