### ISSUE TITLE
Allowing for tokens without pos-tagging (new title)

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#16]
I got an error when trying to create a weighted token matrix. I'm keeping the screenshot at the end of the comment but now I think I understand the problem so I'm laying it out here with a suggested solution first.
`make_tc_weight_matrix` identifies the type corresponding to a token by splitting the token id in each '/' and getting the first two elements. These two elements, normally, would be lemma and part of speech, but in this case it fails because I'm not using part of speech. So it selects wordform and filename, which of course match no type, thus I get a Value Error of 'empty input matrix'.

Is there a way around it?
I'm thinking that, if a token id will always have filename and position as the two last sections (separated by '/'), instead of defining the type as the first two sections we could define it as everything but the last two? Then it wouldn't matter if it's wordform, lemma, or lemma with part of speech or whatever...
My suggestion then is to change line 943 of Manager.py to:
```
type = '/'.join(token.split('/')[:-2])
```
Would that work? I don't dare make the change myself.

===============================================================
**This is the original problem:**
I got the following error when trying to create a weight matrix. I didn't get it with COHA, so the problem must be in my data, but I don't understand where and why.
![image](https://user-images.githubusercontent.com/16564533/40834127-496bfa5c-6590-11e8-8129-6352029b1c84.png)

Neither the token-context matrix nor the pmi matrix seem to be 'empty', so I don't know where the problem lies nor how to detect it. Why does it think that the input matrix is a dict?

![image](https://user-images.githubusercontent.com/16564533/40834182-6d3d3112-6590-11e8-90b2-539a0bcb7fc7.png)

**Comment by delhikiev** [comment]
I think I figured out the problem!
`make_tc_weight_matrix` identifies the type corresponding to a token by splitting the token id in each '/' and getting the first two elements. These two elements, normally, would be lemma and part of speech, but in this case it fails because I'm not using part of speech. So it selects wordform and filename, which of course match no type, thus an 'empty input matrix'.

Is there a way around it?
I'm thinking that, if a token id will always have filename and position as the two last sections (separated by '/'), instead of defining the type as the first two sections we could define it as everything but the last two? Then it wouldn't matter if it's wordform, lemma, or lemma with part of speech or whatever...
My suggestion then, in line 943 of Manager.py:
```
type = '/'.join(token.split('/')[:-2])
```
Would that work? I don't dare make the change myself.

**Comment by enzocxt** [comment]
Yes, your idea is a very good solution. I have updated the code.  
And the new _typetoken_ model which is now in _/home/aardvark/code/typetokenQLVL/typetoken_ on the server, would pull every update from github repository. We do not modify anything local on the server in order to make updates consistent (every time if there would be an update, before pushing it to github I do many tests to make sure the new update would not affect other functions of the model).  
But there is another way to make it possible for you to modify the code and try to solve bugs you find in your research. Copy the _/home/aardvark/code/typetokenQLVL/typetoken_ directory to a directory in your local home directory. And modify the model path to your new path. Then you can change the code in you own typetoken directory and try to solve bugs.  
Here is an example. Assume you copy the typetoken directory to _/home/mariana/typetokenQLVL/typetoken_. In your research script, do the following modification.  
```python
sys.path.append("/home/mariana/typetokenQLVL")
```
This line of code appears in the very head of example snippet script. Then the typetoken model you are using is your own one. You can modify this model to make your research code work. When you find solution to bugs, inform me and I will update it to our github repository.
