### ISSUE TITLE
Messed up data with tcMTX.sample()

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#19]
This may be related to Issue #14 
When I get a sample from a token_context_position matrix, the values get messed up. Those from the original matrix are ok, those from the sample are not.

![image](https://user-images.githubusercontent.com/16564533/43141081-59c34af6-8f55-11e8-8ee2-668dcd9a28cf.png)

From a token_context_weight matrix, though, it remains correct.

**Comment by delhikiev** [comment]
The problem persists in the python3 version, at least for the tcMTX, before weighting.

![image](https://user-images.githubusercontent.com/16564533/44035186-2c0baba2-9f0f-11e8-8852-8e03bcb52e43.png)

**Comment by enzocxt** [comment]
Hi Mariana,

I just fix (possibly) the issue. There was a stupid bug in my code.
You can rerun and test it now.

Best,
Tao

**Comment by delhikiev** [comment]
Yes, it’s fixed! Thanks!

**Comment by delhikiev** [comment]
Something else: if I want to modify the filename when saving a matrix, do I just pass it as an argument to the save method, or does it need to be ‘filename=…’ or something?

**Comment by enzocxt** [comment]
Pass it just as an argument, not ‘filename=…’.

Another note:
If you use filename like ‘/xxx/COHA.wcmx.freq’, the method will automatically add an extension of ‘.pac’ (we should also discuss about a better extension of this).
If you use filename with extension ‘/xxx/COHA.wcmx.freq.pac’, this will be your final filename.

And be careful to the filenames, since we previously use filenames like ‘/xxx/COHA.wcmx.freq.json’.
If you pass this to the methods, then the final filename would be ‘/xxx/COHA.wcmx.freq.json.pac’. That’s a wired filename.

**Comment by delhikiev** [comment]
I actually passed a name ending in ‘pac’ and so the filename ended in ‘pac.pac’…

One other thing I just noticed: make_tc_weight_matrix is again a method of tvman, not TCMatrix, so I need to generate tvman again if I leave the workflow before this method (it’s not enough loading the tcmatrix, I also need tvman)

**Comment by enzocxt** [comment]
Ended in ‘pac.pac’? That’s wired. So pass filenames without ‘.pac’ extension currently. I will fix it.

My mistake. It’s not clear in the snippets.
make_tc_weight_matrix is a class method of TokVecManager class.
You can use it directly by TokVecManager.make_tc_weight_matrix(), not by the tvman object.
After loading the tc_position_matrix from file, you pass the tc_position_matrix and type weight matrix to this method.
Then you don’t need to rerun tvman.
